version: '3.8'

services:
    postgresql:
        image: postgres:14
        container_name: postgres-db
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: admin
            POSTGRES_USER: admin123
            POSTGRES_DB: db_agency
        volumes:
            - postgres_data:/var/lib/postgresql/data

    pgadmin:
        image: dpage/pgadmin4:latest
        environment:
            PGADMIN_DEFAULT_EMAIL: "admin@gmail.com"
            PGADMIN_DEFAULT_PASSWORD: "admin"
        ports:
            - 5050:80
        depends_on:
            - postgresql
        volumes:
            - pgadmin_data:/var/lib/pgadmin

volumes:
    postgres_data:
        driver: local
    pgadmin_data:
        driver: local
